'use client';

import React from 'react';

// Generated by scripts/optimize-images.mjs: per source image its intrinsic size and
// the AVIF/WebP widths available under `base` (e.g. /_img/images/projects/x.640.avif).
type ImageEntry = { w: number; h: number; base: string; widths: number[] };

let manifest: Record<string, ImageEntry> = {};
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  manifest = require('../../../public/_img/manifest.json');
} catch {
  manifest = {};
}

export function getImageEntry(src: string): ImageEntry | undefined {
  const entry = manifest[src.startsWith('/') ? src : '/' + src];
  return entry && Array.isArray(entry.widths) ? entry : undefined;
}

export function buildSrcSet(src: string, format: 'avif' | 'webp'): string | undefined {
  const entry = getImageEntry(src);
  if (!entry) return undefined;
  return entry.widths.map((w) => `${entry.base}.${w}.${format} ${w}w`).join(', ');
}

export interface ResponsiveImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  src: string;
  alt: string;
  priority?: boolean;
  sizes?: string;
  className?: string;
}

/**
 * <picture> with AVIF and WebP at several widths: the browser downloads the smallest
 * file that covers `sizes × devicePixelRatio` (quality-gated, visually identical to
 * the original). The original file is only the last-resort fallback (no AVIF/WebP
 * support, or no manifest in dev). `picture { display: contents }` keeps existing
 * `parent > img` CSS working.
 */
export function ResponsiveImage({
  src,
  alt,
  priority = false,
  sizes = '(max-width: 640px) 100vw, (max-width: 1280px) 50vw, 33vw',
  className,
  width,
  height,
  ...props
}: ResponsiveImageProps) {
  // No image (e.g. an article whose cover was removed): a branded placeholder in the
  // same box instead of a broken image.
  if (!src) {
    return <span className={`${className || ''} img-placeholder`} role="img" aria-label={alt || ''} />;
  }
  const entry = getImageEntry(src);

  const img = (
    <img
      src={src}
      width={width || entry?.w || undefined}
      height={height || entry?.h || undefined}
      alt={alt || ''}
      loading={priority ? 'eager' : 'lazy'}
      fetchPriority={priority ? 'high' : 'auto'}
      decoding="async"
      className={className}
      {...props}
    />
  );

  if (!entry) return img;

  return (
    <picture>
      <source type="image/avif" srcSet={buildSrcSet(src, 'avif')} sizes={sizes} />
      <source type="image/webp" srcSet={buildSrcSet(src, 'webp')} sizes={sizes} />
      {img}
    </picture>
  );
}

export default ResponsiveImage;
